hw/riscv/riscv_board.c
target-riscv/op_helper.c

These patches enable compatibility with the riscv-linux master branch.
QEMU guest support should now only require a different set of built-in drivers.

Normalize IRQ behavior

---

hw/riscv/cputimer.c

This allows us to use the same Linux timer driver between QEMU and
Rocket.

Set the correct timer frequency

---

hw/riscv/riscv_board.c

With this option a coreboot image built for coreboot's
emulation/qemu-riscv target can be run successfully using
$ qemu-system-riscv -bios coreboot.rom
Signed-off-by: Patrick Georgi <pgeorgi@google.com>

riscv: enable -bios option

---

disas/riscv.c
fpu/softfloat-specialize.h
hw/riscv/htif/elf_symb.c
hw/riscv/htif/elf_symb.h
hw/riscv/htif/frontend.c
hw/riscv/htif/htif.c
hw/riscv/riscv_board.c
hw/riscv/riscv_int.c
hw/riscv/riscv_rtc.c
hw/riscv/riscv_softint.c
include/elf.h
include/hw/riscv/htif/frontend.h
include/hw/riscv/htif/htif.h
include/hw/riscv/riscv_rtc.h
include/hw/riscv/riscv_softint.h
target-riscv/cpu.c
target-riscv/cpu.h
target-riscv/gdbstub.c
target-riscv/helper.c
target-riscv/helper.h
target-riscv/instmap.h
target-riscv/op_helper.c
target-riscv/translate.c
target-riscv/translate_init.c

Hey Sagar,
I'm mostly finished with my cleanups and it now runs through checkpatch.pl without too much trouble. 
I basically have three types of problems left:
1) ERROR: externs should be avoided in .c files
#4075: FILE: target-riscv/helper.c:35:
int validate_priv2(target_ulong priv);
I guess this needs some redesign of the functions and I'm not quite sure how to do it, without breaking too much :)
2) ERROR: braces {} are necessary for all arms of this statement
#5013: FILE: target-riscv/op_helper.c:98:
#define RM ({ if (rm == 7) rm = env->csr[CSR_FRM]; \
Checkpatch doesn't like this kind of makro definition and I'm not 100% sure on how to change it.
3) ERROR: if this code is redundant consider removing it
#3953: FILE: target-riscv/gdbstub.c:101:
+#if 0
I wasn't sure here if this could be …

Upstream cleanup

---

target-riscv/helper.h
target-riscv/op_helper.c
target-riscv/translate.c

calling a helper is expensive, so lets make at least mulhsu for RV32 use tcg-ops.
Signed-off-by: Bastian Koppelmann <kbastian@mail.uni-paderborn.de>

target-riscv: Optimize mulhsu

---

README.md
hw/riscv/Makefile.objs
hw/riscv/sifive_board.c
hw/riscv/sifive_uart.c
include/hw/riscv/cpudevs.h
include/hw/riscv/sifive_uart.h

This is mostly the same code I sent you on Sep 11, but it's now in a new "sifive" board; the existing board is not modified except to make clear that it's a Spike board.  New board has a UART and removes HTIF.  Also includes directions about how to use it; might be a good idea to sanity-check it.
The SiFive SDK is capable of running on the Spike board as well; you'll be able to tell which you're using because of the flow control problem with the HTIF console (try pasting a small amount of text or using the arrow keys).
Also I don't know what the memory map on the actual hardware is; I'm going entirely off of the device drivers.
Also fixed the README to mention that the docker image is based on F25 (next stable), not F24 (current stable).

Add SiFive SDK-compatible board

---

linux-user/signal.c

With these changes parallel gcc builds now work, as well as some ad-hoc sigaltstack tests.
Test program which demonstrates all of the fixes (except unlock_user_struct, which is only relevant with DEBUG_REMAP)
```
#include <signal.h>
#include <string.h>
#include <stdio.h>
#include <unistd.h>
char altstack[2][65536];
void pstack(char* where) {
int var;
char buf[256];
stack_t ss2;
sigaltstack(0,&ss2);
sprintf(buf, "%s, sp=%lx, altsp=%lx, altfl=%x\n", where, (long)&var, (long)ss2.ss_sp, (int)ss2.ss_flags);
write(2, buf, strlen(buf));
}
void setstack(int which) {
stack_t ss;
ss.ss_flags = 0;
ss.ss_size=sizeof(altstack[which]);
ss.ss_sp=&altstack[which][0];
sigaltstack(&ss,0);
}
void usr1hand2(int sig) {
pstack("enter usr1/2");
setstack(1);
pstack("exit usr1/2");
}
void usr1hand(int sig) { …
```

Fix sigreturn

---

target-riscv/user_atomic.c

We seem to already be compiling with `-fwrapv`, so this shouldn't introduce new undefined behavior.

Make lr.w and sc.w do sign extension.  Fixes riscv/riscv-gcc#23

---

linux-user/signal.c

In addition to just being an out of bounds access, the upshot of this is
that t6 was being overwritten with ft0 on every signal.  This was
causing the git crashes; closes #38.

Fix off-by-one error in sigcontext operations

---

README.md
hw/riscv/htif/htif.c
hw/riscv/riscv_board.c
hw/riscv/riscv_rtc.c
hw/riscv/sifive_board.c
target-riscv/helper.c
target-riscv/init.c
target-riscv/translate.c

This contains @kito-cheng's #45 .
With this patch I was able to build riscv-qemu and sifive-u-sdk in an i686 Debian chroot and then boot Linux with the initramfs.
@shrshore May be of interest to you… note, the emulated RISC-V environment is still 64-bit, so you will use the riscv64-* tools.

Fixes for RV64 on ILP32 hosts

---

linux-user/elfload.c

Reverts arsv/riscv-qemu@6268f398; this should fix the observed segfaults
on statically linked binaries with the new linker script.
I have *not tested this* but it is offered as a fix for riscv/riscv-binutils-gdb#52 .

Remove brk special handling

---

hw/riscv/sifive_board.c

At the moment the qemu sifive board 'riscv_sifive_board.ram'
region overlap devices regions.
E.g. please see 'info mtree' qemu monitor command output:
(qemu) info mtree
address-space: memory
0000000000000000-ffffffffffffffff (prio 0, RW): system
0000000000000000-0000000087ffffff (prio 0, RW):
riscv_sifive_board.ram
0000000040000000-000000004000000f (prio 0, RW): timer
0000000040002000-000000004000200f (prio 0, RW): riscv.sifive_uart
address-space: I/O
0000000000000000-000000000000ffff (prio 0, RW): io
address-space: cpu-memory
0000000000000000-ffffffffffffffff (prio 0, RW): system
0000000000000000-0000000087ffffff (prio 0, RW): riscv_sifive_board.ram
0000000040000000-000000004000000f (prio 0, RW): timer
0000000040002000-000000004000200f (prio 0, RW): riscv.sifive_uart
Here is the memory …

hw/sifive_board: set correct base address for RAM region

---

README.md
hw/riscv/sifive_uart.c

Fixes #54.  Still not implemented: TX flow control, interrupts,
configuration registers; but this is enough for bbl.

Update UART model to match shipped FE310

---

target-riscv/op_helper.c

The Go port wants to use `rdtime a0` in one place, which we currently aren't handling.

target-riscv: Add timer support for user-mode emulation

---

linux-user/main.c

Not quite right as we're not advancing the PC, but it's better than an
assertion failure.

EBREAK should cause SIGTRAP

---

hw/riscv/spike_v1_10.c

@sagark this is essential to merge due to a breaking change made in bbl in the last couple of weeks. 
Can you please merge this ASAP. It is a low risk change. It just adds an HTIF node to device-tree for the spike-v1.10 board so that we can run top of tree. It's a backwards compatible change. I'ts in the plic branch but i've cherry-picked it so we can get this fix in for the distro builders. It's required to run the spike kernel image from top of tree freedom-u-sdk.
```
$ qemu-system-riscv64 -nographic -machine spike_v1.10,dumpdtb=spike.dts
$ fdtdump spike.dts 
**** fdtdump is a low-level debugging tool, not meant for general use.
**** If you want to decompile a dtb, you probably want
****     dtc -I dtb -O dts <filename>
/dts-v1/;
// magic:		0xd00dfeed
// totalsize:		0x10000 (65536)
// …
```

[spike_v1.10] add device tree htif node

---

hw/riscv/sifive_u500.c
hw/riscv/spike_v1_10.c
hw/riscv/virt.c

This patch leverages the linux kernel device-tree command line processing code https://github.com/riscv/riscv-linux/blob/50c4c4e268a2d7a3e58ebb698ac74da0de40ae36/drivers/of/fdt.c#L1095-L1098
With this patch, the user can pass -append "root=/dev/vda ro console=ttyS0" to select root device and console device, instead of hardcoding in CONFIG_CMDLINE e.g.
```
sudo qemu-system-riscv64 -nographic -machine vir \
-kernel bbl -append "root=/dev/vda console=ttyS0 ro" \
-drive file=root.bin,format=raw,id=hd0 \
-device virtio-blk-device,drive=hd0 \
-netdev type=tap,script=./ifup,downscript=./ifdown,id=net0 \
-device virtio-net-device,netdev=net0 
```

Add support for passing kernel command line using -append

---

block/blkdebug.c
block/blkverify.c
hw/usb/bus.c
net/slirp.c
ui/gtk.c

Here are another 6 backports from upstream to get rid of errors/warnings on Fedora 26/27:
- https://github.com/qemu/qemu/commit/f95cc8b6cc3ad8c4b687f305a978d67091c28138
- https://github.com/qemu/qemu/commit/76d8f93b4a72d02f6af6ff4eda36b7630cd8417b
- https://github.com/qemu/qemu/commit/82a4f1a96ed6be87c0ef6d4393b22085751bd450
- https://github.com/qemu/qemu/commit/121829cb2160e9cd82482c1542699fa589688106
- https://github.com/qemu/qemu/commit/05cc758a3dfc79488d0a8eb7f5830a41871e78d0
- https://github.com/qemu/qemu/commit/de81d72d3d13a19edf4d461be3b0f5a877be0234
The only warnings/errors which are left are within xen part.
Build tested on Fedora 27 together with https://github.com/riscv/riscv-qemu/pull/78 and 
```
./configure --target-list=riscv64-softmmu,riscv32-softmmu --disable-xen
``` …

Backports from upstream

---

target/riscv/cpu.c

Delete set_default_nan_mode call in riscv_cpu_reset.

RISC-V: Use IEEE NaNs instead of default NaNs.

---

configure
hw/riscv/riscv_htif.c
hw/riscv/sifive_clint.c
hw/riscv/sifive_plic.c
hw/riscv/spike_v1_09.c
hw/riscv/spike_v1_10.c
include/hw/riscv/riscv_htif.h
target/riscv/cpu.c
target/riscv/cpu.h
target/riscv/cpu_bits.h
target/riscv/helper.c
target/riscv/op_helper.c

I expect these to be squashed as part of the v6 so the commit messages are targeted to reviewers.  DJ Delorie and myself have given the first commit here of about 6-12 hours of load testing under mttcg; the remaining cleanups are not as well tested, but do boot (virt, spike_v1.9, spike_v1.10).

cleanup and locking improvement for local interrupts

---

target/riscv/cpu.h
target/riscv/helper.c

The RISC-V Privileged Specification requires that updates
to PTE accessed and dirty bits are atomic. There is a small
race window in the current code between reading the PTE and
updating it. The only reasonable way to make updates atomic
is to use atomic_cmpxchg. To use platform atomics, we need
to translate the guest physical address to a host address.
In the rare case that the atomic_cmpxchg of the PTE fails,
it means the PTE is stale, and we must restart the walk. The
PTE may longer be valid, the permissions may have changed
or the PTE may even point to another physical page. The
simplist approach to handling a conflict is to re-walk
the page tables for the current translation. This is safe
and fast as the likelihood the PTE is stale is rare.
Maliciously crafted supervisor code could …

RISC-V - Make updates to PTE accessed and dirty bits atomic

---

target/riscv/translate.c

If there is an instruction like "sfence.vma x0, xx" where xx != x0,
the csr value (bit[31:20]) won't match 0x120.
funct7 value (at bit[31:25]) needs to be checked first.

Fix a bug when sfence.vma is passed (rs2) arguments

---

fpu/softfloat.c

@sorear Merging softfloat: fix crash on int conversion of SNaN into qemu-all

softfloat: fix crash on int conversion of SNaN

---

target/riscv/cpu.c

Fix memory size calculation logic bug in riscv_isa_string. 
```
==17441== Invalid write of size 1
==17441==    at 0x26517F: riscv_isa_string (cpu.c:399)
==17441==    by 0x25C14D: create_fdt (spike.c:125)
==17441==    by 0x25C14D: spike_v1_10_0_board_init (spike.c:199)
==17441==    by 0x2CCE0A: machine_run_board_init (machine.c:807)
==17441==    by 0x1BFF28: main (vl.c:4597)
==17441==  Address 0x3055c425 is 0 bytes after a block of size 5 alloc'd
==17441==    at 0x4C2FB55: calloc (in
/usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==17441==    by 0x70C8770: g_malloc0 (in
/lib/x86_64-linux-gnu/libglib-2.0.so.0.4800.2)
==17441==    by 0x26511E: riscv_isa_string (cpu.c:395)
==17441==    by 0x25C14D: create_fdt (spike.c:125)
==17441==    by 0x25C14D: spike_v1_10_0_board_init (spike.c:199) …
```

RISC-V: Fix isa string logic bug, use popcount to count bits

---

hw/riscv/Makefile.objs
hw/riscv/boot.c
hw/riscv/virt.c
include/hw/riscv/boot.h

Support for separate firmware and kernel payload is added
by updating BBL to read optional preloaded kernel address
attributes from device-tree using a similar mechanism to
that used to pass init ramdisk addresses to linux kernel.
chosen {
riscv,kernel-start = <0x00000000 0x80200000>;
riscv,kernel-end = <0x00000000 0x80590634>;
};
These attributes are added by QEMU and read by BBL when combining
`-bios <firmware-image>` and `-kernel <kernel-image>` options. e.g.
```
$ qemu-system-riscv64 -machine virt -bios bbl -kernel vmlinux
```
With this change, bbl can be compiled without `--with-payload`
and the dummy payload alignment is altered to make the memory
footprint of the firmware-only bbl smaller. The dummy payload
message is updated to indicate the alternative load method.
This load …

RISC-V: Support separate firmware and kernel payload

---

hw/riscv/sifive_prci.c
hw/riscv/sifive_uart.c
include/hw/riscv/sifive_prci.h
include/hw/riscv/sifive_uart.h

Store writes to Sifive PRCI registers while maintaining oscillator ready/lock bits
Emulate the UART IP (interrupt pending) register

Improve emulation of Sifive PRCI and UART Memory-Mapped Registers
